### ISSUE TITLE
2.0.3 unavailable on Maven

### ISSUE THREAD

**Issue by anuraagvaidya** [kwhat/jnativehook#107]
I couldn't find the 2.0.3 release on Maven. I've grabbed the zip from releases, but just reminding ^_^.

**Comment by kwhat** [comment]
I pushed it back up again, has this fixed the issue?

```
      [mvn] [INFO] Scanning for projects...
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] Building JNativeHook
      [mvn] [INFO]    task-segment: [org.apache.maven.plugins:maven-gpg-plugin:1.6:sign-and-deploy-file] (aggregator-style)
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] [gpg:sign-and-deploy-file {execution: default-cli}]
      [mvn] Uploading: https://oss.sonatype.org/service/local/staging/deploy/maven2/com/1stleg/jnativehook/2.0.3/jnativehook-2.0.3.jar
      [mvn] 188K uploaded  (jnativehook-2.0.3.jar)
      [mvn] [INFO] Retrieving previous metadata from ossrh
      [mvn] [INFO] repository metadata for: 'artifact com.1stleg:jnativehook' could not be found on repository: ossrh, so will be created
      [mvn] [INFO] Uploading repository metadata for: 'artifact com.1stleg:jnativehook'
      [mvn] [INFO] Uploading project information for jnativehook 2.0.3
      [mvn] [INFO] Uploading jnativehook-2.0.3.jar.asc
      [mvn] [INFO] Uploading jnativehook-2.0.3.pom.asc
      [mvn] [INFO] Metadata[artifact com.1stleg:jnativehook].filename = maven-metadata.xml
      [mvn] [INFO] Metadata[project com.1stleg:jnativehook].filename = jnativehook-2.0.3.pom
      [mvn] [INFO] Metadata[gpg signature com.1stleg:jnativehook:jar:null].filename = jnativehook-2.0.3.jar.asc
      [mvn] [INFO] Metadata[gpg signature com.1stleg:jnativehook:jar:null:pom].filename = jnativehook-2.0.3.pom.asc
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] BUILD SUCCESSFUL
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] Total time: 9 seconds
      [mvn] [INFO] Finished at: Sun Jul 31 08:08:26 PDT 2016
      [mvn] [INFO] Final Memory: 23M/163M
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] Scanning for projects...
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] Building JNativeHook
      [mvn] [INFO]    task-segment: [org.apache.maven.plugins:maven-gpg-plugin:1.6:sign-and-deploy-file] (aggregator-style)
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] [gpg:sign-and-deploy-file {execution: default-cli}]
      [mvn] Uploading: https://oss.sonatype.org/service/local/staging/deploy/maven2/com/1stleg/jnativehook/2.0.3/jnativehook-2.0.3-sources.jar
      [mvn] 244K uploaded  (jnativehook-2.0.3-sources.jar)
      [mvn] [INFO] Retrieving previous metadata from ossrh
      [mvn] [INFO] Uploading repository metadata for: 'artifact com.1stleg:jnativehook'
      [mvn] [INFO] Uploading project information for jnativehook 2.0.3
      [mvn] [INFO] Uploading jnativehook-2.0.3.pom.asc
      [mvn] [INFO] Uploading jnativehook-2.0.3-sources.jar.asc
      [mvn] [INFO] Metadata[artifact com.1stleg:jnativehook].filename = maven-metadata.xml
      [mvn] [INFO] Metadata[project com.1stleg:jnativehook].filename = jnativehook-2.0.3.pom
      [mvn] [INFO] Metadata[gpg signature com.1stleg:jnativehook:jar:sources:pom].filename = jnativehook-2.0.3.pom.asc
      [mvn] [INFO] Metadata[gpg signature com.1stleg:jnativehook:jar:sources].filename = jnativehook-2.0.3-sources.jar.asc
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] BUILD SUCCESSFUL
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] Total time: 3 seconds
      [mvn] [INFO] Finished at: Sun Jul 31 08:08:30 PDT 2016
      [mvn] [INFO] Final Memory: 22M/163M
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] Scanning for projects...
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] Building JNativeHook
      [mvn] [INFO]    task-segment: [org.apache.maven.plugins:maven-gpg-plugin:1.6:sign-and-deploy-file] (aggregator-style)
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] [gpg:sign-and-deploy-file {execution: default-cli}]
      [mvn] Uploading: https://oss.sonatype.org/service/local/staging/deploy/maven2/com/1stleg/jnativehook/2.0.3/jnativehook-2.0.3-javadoc.jar
      [mvn] 157K uploaded  (jnativehook-2.0.3-javadoc.jar)
      [mvn] [INFO] Retrieving previous metadata from ossrh
      [mvn] [INFO] Uploading repository metadata for: 'artifact com.1stleg:jnativehook'
      [mvn] [INFO] Uploading project information for jnativehook 2.0.3
      [mvn] [INFO] Uploading jnativehook-2.0.3.pom.asc
      [mvn] [INFO] Uploading jnativehook-2.0.3-javadoc.jar.asc
      [mvn] [INFO] Metadata[artifact com.1stleg:jnativehook].filename = maven-metadata.xml
      [mvn] [INFO] Metadata[project com.1stleg:jnativehook].filename = jnativehook-2.0.3.pom
      [mvn] [INFO] Metadata[gpg signature com.1stleg:jnativehook:jar:javadoc:pom].filename = jnativehook-2.0.3.pom.asc
      [mvn] [INFO] Metadata[gpg signature com.1stleg:jnativehook:jar:javadoc].filename = jnativehook-2.0.3-javadoc.jar.asc
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] BUILD SUCCESSFUL
      [mvn] [INFO] ------------------------------------------------------------------------
      [mvn] [INFO] Total time: 3 seconds
      [mvn] [INFO] Finished at: Sun Jul 31 08:08:33 PDT 2016
      [mvn] [INFO] Final Memory: 29M/247M
      [mvn] [INFO] ------------------------------------------------------------------------
```

**Comment by salamatin** [comment]
It's still not available: https://search.maven.org/#search%7Cga%7C1%7Cjnativehook

**Comment by kwhat** [comment]
I really dislike maven.  I have pushed this jar to central twice, released it twice, I can see if it in the Nexus Repository Manager, yet is still not available.  I am not sure how you would make this process any more convoluted.

**Comment by kwhat** [comment]
Alright looks like its showing up in the search now.
