### ISSUE TITLE
com.github.kwhat.jnativehook cannot be resolved to a module

### ISSUE THREAD

**Issue by srilakshmikanthanp** [kwhat/jnativehook#390]
Hai, I want to use this library for keyboard listening but when I am add it to module it shown no module found here the module-info.java

~~~java
module facsimile 
{
    // from java
    requires java.prefs;

    // from gson
    requires com.google.gson;

    // from jnativehook
    requires com.github.kwhat.jnativehook;

    // from javafx
    requires javafx.controls;

    // give access to the facsimile package
    opens com.github.srilakshmikanthanp.facsimile to javafx.graphics;
}

And here is my maven dependency
 
~~~
    <dependency>
      <groupId>com.github.kwhat</groupId>
      <artifactId>jnativehook</artifactId>
      <version>2.2.1</version>
    </dependency>
~~~

**Comment by kwhat** [comment]
Need more information, error message, example project.

**Comment by srilakshmikanthanp** [comment]
Thanks for your Replay, Here is the deme maven project that reproduces the error [demo.zip](https://github.com/kwhat/jnativehook/files/7775282/demo.zip) and i am using jdk 17.

**Comment by kwhat** [comment]
The problem appears to be that maven didn't create the correct manifest for a multi-release jar. _I'm shocked._ It should contain `Multi-Release: true`

**Comment by kwhat** [comment]
Resolved in the latest 2.2-SNAPSHOT, let me know if there are more problems.

**Comment by srilakshmikanthanp** [comment]
Hai, I still having issues with the module, it would be appreciated if you give the updated [demo.jar](https://github.com/kwhat/jnativehook/files/7775282/demo.zip) that works fine.

**Comment by srilakshmikanthanp** [comment]
Hello, I have temporarily Fixed the Error by manually installing the jar file of snapshot, Thanks
