### ISSUE TITLE
Media keys posting not working

### ISSUE THREAD

**Issue by Azenet** [kwhat/jnativehook#83]
Hi,

I am trying to simulate media key presses under Windows. I downloaded the 2.0.3 release from Github.
My code is as follows :
```java
NativeKeyEvent ev = new NativeKeyEvent(
	NativeKeyEvent.NATIVE_KEY_PRESSED,
	System.currentTimeMillis(),
	0x00,
	0x00,
	NativeKeyEvent.VC_MEDIA_PLAY,
	NativeKeyEvent.CHAR_UNDEFINED,
	NativeKeyEvent.KEY_LOCATION_STANDARD);

GlobalScreen.registerNativeHook();
GlobalScreen.addNativeKeyListener(new NativeKeyListener() {
	@Override
	public void nativeKeyPressed(NativeKeyEvent nativeKeyEvent) {
		System.out.println("Pressed: " + nativeKeyEvent.getKeyCode() + ":" + nativeKeyEvent.getRawCode());
	}

	@Override
	public void nativeKeyReleased(NativeKeyEvent nativeKeyEvent) {

	}

	@Override
	public void nativeKeyTyped(NativeKeyEvent nativeKeyEvent) {

	}
});
GlobalScreen.postNativeEvent(ev);
```

This will display "Pressed: 34:71" (or 0x22:0x47) and will press the letter G on the keyboard. However if I press the media key on my physical keyboard it will display "Pressed: 57378:179" (or 0xE022:0xB3), which is the expected `VC_MEDIA_PLAY` code.

Thanks.

**Comment by kwhat** [comment]
Sounds like a bug ;S I am guessing the map file is off for that key.  I will take a look this weekend.

**Comment by Azenet** [comment]
Thanks. This behavior seems to happen with all the VC_MEDIA keys.

**Comment by kwhat** [comment]
The best thing you can do is toString() the NativeInputEvent object and log all the keys that aren't working.  Be sure to document what each key is because I will have no idea based on the toString() output..

**Comment by kwhat** [comment]
Sorry for the delay, I have been trying to get my system working after the Plasma 5 upgrade and it has taken a while.  Upstream 3e57663 should solve the problem you are having.  Source is available in the 2.0 branch and will be released as 2.0.4 soon.  Nightly is here: https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.0.SNAPSHOT/jnativehook-2.0.20160118.013353-32.jar

**Comment by Azenet** [comment]
Thanks, but unfortunately this doesn't seem to fix it. I am still getting "Pressed 34:71".

I never saw your request for the toString() of the NativeInputEvent object, but it doesn't say much: `org.jnativehook.keyboard.NativeKeyEvent[source=class org.jnativehook.GlobalScreen]`

And only to make sure I'm not doing something wrong, is the way I'm creating the event still correct ?
```java
NativeKeyEvent ev = new NativeKeyEvent(
		NativeKeyEvent.NATIVE_KEY_PRESSED,
		System.currentTimeMillis(),
		0x00,
		0x00,
		NativeKeyEvent.VC_MEDIA_PLAY,
		NativeKeyEvent.CHAR_UNDEFINED,
		NativeKeyEvent.KEY_LOCATION_STANDARD);
```

**Comment by andre111** [comment]
Is this still being looked into?

I just ran into this problem as well. I've been successfully using jnativehook for detecting media key presses but recently I also started to need to "press" them.

I didn't test a lot of keys, but definitelly all media and volume keys result in wrong keys being pressed.

**Comment by kwhat** [comment]
@andre111 which OS? It's been awhile since I looked at this, but it's something that will be fixed as soon as I figure out where the problem is.

**Comment by andre111** [comment]
Windows 10
pretty sure it also occured on Windows 7 bu I currently no longer have a Win7 computer to test it with.

**Comment by Azenet** [comment]
My issue is with Windows 7, so it does happen.

**Comment by kwhat** [comment]
Alright, I have found the root cause of the issue and it effects several other keys.  I am going to write some tests to try and find thous keys.

**Comment by kwhat** [comment]
Do either of you have a VC_APP_PICTURES or VC_APP_MUSIC button?

**Comment by kwhat** [comment]
Try this https://oss.sonatype.org/content/repositories/snapshots/com/1stleg/jnativehook/2.1.SNAPSHOT/

**Comment by andre111** [comment]
Works perfect with all keys needed in my application(play,pause,stop and volume controlls).
I don't have time to test others right now

**Comment by kwhat** [comment]
I am going to call this one done.  Thanks for the help.
